# Generated by Django 3.2 on 2024-03-26 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=2200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('ContactChoices', models.CharField(choices=[('1', 'Business inquiries'), ('2', 'Report user'), ('3', 'Feedback about website'), ('4', 'Other questions')], default='4', max_length=1)),
            ],
        ),
    ]
